# Generated by Django 5.2.7 on 2025-11-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="members_count",
        ),
        migrations.AddField(
            model_name="club",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
